// <auto-generated />
using Inventory.Service.API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventory.Service.API.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20240703173844_DBInit")]
    partial class DBInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Inventory.Service.Database.InventoryEntity", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<int>("unit")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Inventory");

                    b.HasData(
                        new
                        {
                            id = "0cdeaf69aa77441ab9e2db9a1ad411e7",
                            name = "Iphone",
                            price = 10f,
                            unit = 5
                        },
                        new
                        {
                            id = "5e28916fdc774fd78a673f2a11765687",
                            name = "Samsung",
                            price = 10f,
                            unit = 5
                        },
                        new
                        {
                            id = "6",
                            name = "Sony",
                            price = 10f,
                            unit = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
